<a href="https://colab.research.google.com/github/Niraj7667/ML-models/blob/main/LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow

In [3]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [13]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [14]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[487, 124, 73, 15], [487, 124, 73, 1], [487, 79, 73, 59], [296, 154, 215, 488, 157], [296, 154, 215, 488, 426], [196, 487, 255, 73, 167], [312, 268, 349, 488]]


### Word Embedding Represntation

In [15]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [ ]:
import numpy as np

In [17]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 487 124  73  15]
 [  0   0   0   0 487 124  73   1]
 [  0   0   0   0 487  79  73  59]
 [  0   0   0 296 154 215 488 157]
 [  0   0   0 296 154 215 488 426]
 [  0   0   0 196 487 255  73 167]
 [  0   0   0   0 312 268 349 488]]


In [18]:
## 10 feature dimesnions
dim=10


In [20]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [21]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [22]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 487, 124,  73,  15], dtype=int32)

In [ ]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 72ms/step


array([[ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03938437, -0.02009605, -0.03878935, -0.04955565,  0.00419912,
        -0.01431773,  0.02523251,  0.01653036,  0.04291571, -0.00864979],
       [ 0.03059326, -0.04286614,  0.00899569,  0.00743791, -0.000781  ,
         0.04186494,  0.03977301,  0.00326709,  0.00619651, -0.01993654],
       [ 0.02512412, -0.0087087 ,  0.03144198,  0.00704668, -0.00177735,
        -0.03415867, -0.00100178,  0.01562483,  0.03178963,  0.02784893],
       [-0.00653008,  0.02340979, -0.01967902, -0.00494973, -0.02693756,
        -0.03746525,  0.01460877, -0.00449115

In [23]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 900ms/step
[[[ 3.74207012e-02  6.90812990e-03  5.25091961e-03  3.22087295e-02
   -2.76272893e-02 -1.23854391e-02  2.95639038e-05 -1.93890091e-02
    4.78644632e-02 -2.40914822e-02]
  [ 3.74207012e-02  6.90812990e-03  5.25091961e-03  3.22087295e-02
   -2.76272893e-02 -1.23854391e-02  2.95639038e-05 -1.93890091e-02
    4.78644632e-02 -2.40914822e-02]
  [ 3.74207012e-02  6.90812990e-03  5.25091961e-03  3.22087295e-02
   -2.76272893e-02 -1.23854391e-02  2.95639038e-05 -1.93890091e-02
    4.78644632e-02 -2.40914822e-02]
  [ 3.74207012e-02  6.90812990e-03  5.25091961e-03  3.22087295e-02
   -2.76272893e-02 -1.23854391e-02  2.95639038e-05 -1.93890091e-02
    4.78644632e-02 -2.40914822e-02]
  [ 1.24138482e-02 -2.40385775e-02  4.35067154e-02  3.39941494e-02
    2.94023491e-02 -9.75149870e-03  2.29061358e-02 -2.42879279e-02
   -1.13171116e-02  1.34233721e-02]
  [ 2.15178467e-02  2.70328633e-02  2.89572403e-03 -1.02014430e-02
    2.20366381e-02 -9.26465914e-03  6.070148

In [24]:
embedded_docs[0]

array([  0,   0,   0,   0, 487, 124,  73,  15], dtype=int32)

In [25]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
[[ 3.7420701e-02  6.9081299e-03  5.2509196e-03  3.2208730e-02
  -2.7627289e-02 -1.2385439e-02  2.9563904e-05 -1.9389009e-02
   4.7864463e-02 -2.4091482e-02]
 [ 3.7420701e-02  6.9081299e-03  5.2509196e-03  3.2208730e-02
  -2.7627289e-02 -1.2385439e-02  2.9563904e-05 -1.9389009e-02
   4.7864463e-02 -2.4091482e-02]
 [ 3.7420701e-02  6.9081299e-03  5.2509196e-03  3.2208730e-02
  -2.7627289e-02 -1.2385439e-02  2.9563904e-05 -1.9389009e-02
   4.7864463e-02 -2.4091482e-02]
 [ 3.7420701e-02  6.9081299e-03  5.2509196e-03  3.2208730e-02
  -2.7627289e-02 -1.2385439e-02  2.9563904e-05 -1.9389009e-02
   4.7864463e-02 -2.4091482e-02]
 [ 1.2413848e-02 -2.4038577e-02  4.3506715e-02  3.3994149e-02
   2.9402349e-02 -9.7514987e-03  2.2906136e-02 -2.4287928e-02
  -1.1317112e-02  1.3423372e-02]
 [ 2.1517847e-02  2.7032863e-02  2.8957240e-03 -1.0201443e-02
   2.2036638e-02 -9.2646591e-03  6.0701482e-03 -6.1162002e-03
  -4.3177523e-02 -2.1642018e-02]
 [ 2.6549529e-02  3.

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]